version: '3'
$schema: https://raw.githubusercontent.com/roadrunner-server/roadrunner/refs/heads/master/schemas/config/3.0.schema.json

rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php app.php'
  relay: pipes
  on_init:
    command: 'php app.php migrate'

http:
  address: '0.0.0.0:8080'
  # ssl:
  #   address: '0.0.0.0:443'

  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    num_workers: 4
    debug: ${DEBUG:-false}
    supervisor:
      max_worker_memory: 256
temporal:
  address: ${TEMPORAL_ADDRESS:-127.0.0.1:7233}
  activities:
    num_workers: 4
    debug: ${DEBUG:-false}
  cache_size: 100

logs:
  level: warn
